config/routes.rb
Rails.application.routes.draw do

  root to: 'offers#index'

  resources :offers, only: [:index]

  namespace :staff do
    resources :offers do
      member do
        get 'disable'
        get 'enable'
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord

  enum status: { disabled: 0, enabled: 1 }

  validates :advertiser_name, :url, :description, :starts_at, :status, presence: true
  validates :advertiser_name, uniqueness: true
  validates :description, length: { maximum: 500 }
  validates :url, url: true

  scope :active, -> { where(status: :enabled ) }

  def active!
    enabled! if can_be_enabled? 
  end

  private

  def can_be_enabled?
    ends_at.blank? || (DateTime.current >= starts_at && DateTime.current <= ends_at)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  responders :flash
  respond_to :html
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_action :set_offers

  def index
  end

  private

  def set_offers
    @offers = Offer.active.order(premium: :desc)
  end

end

app/controllers/staff/offers_controller.rb
class Staff::OffersController < ApplicationController

  before_action :set_offers, only: [:index]
  before_action :set_offer, only: [:edit, :update, :destroy, :disable, :enable]

  def index
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.create(offer_params)
    respond_with(@offer, location: staff_offers_path)
  end

  def edit
  end

  def update
    @offer.update(offer_params)
    respond_with(@offer, location: staff_offers_path)
  end

  def destroy
    @offer.destroy
    respond_with(@offer, location: staff_offers_path)
  end

  def disable
    @offer.disabled!
    redirect_to action: 'index'
  end

  def enable
    @offer.active!
    redirect_to action: 'index'
  end

  private

  def set_offers
    @offers = Offer.order(:starts_at)
  end

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params
      .require(:offer)
      .permit(:advertiser_name, :url, :description, :starts_at, :ends_at, :premium)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/staff/offers_helper.rb
module Staff::OffersHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    title Gamora
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    div class="container"
      - flash.each do |key, value|
        div class="alert alert-#{key}"
          = value
      = yield

app/views/offers/index.slim
div class='page-header'
  h1 = Offer.model_name.human.pluralize

div class='row'
  - @offers.each do |offer|
    div class='col-sm'
      div class='card'
        div class='car-block'
          - if offer.premium?
            span class='badge badge-pill badge-info float-left'
              = Offer.human_attribute_name(:premium)
          - if offer.ends_at.present?
            span class='offer-countdown badge badge-warning float-right' data-ends-at="#{offer.ends_at.strftime('%FT%T%:z')}"
          h3 class='card-title'
            = offer.advertiser_name
          p class='card-text'
            = offer.description
          = link_to t('actions.shop'), offer.url, class: 'btn btn-block btn-primary', target: :_blank

app/views/staff/offers/_form.slim
= simple_form_for([:staff, @offer]) do |f|
  = f.input :advertiser_name
  = f.input :url
  = f.input :description
  = f.input :starts_at
  = f.input :ends_at
  = f.input :premium
  = f.button :submit

app/views/staff/offers/edit.slim
= render 'form'

app/views/staff/offers/index.slim
table class='table'
  thead
    tr
      th = Offer.human_attribute_name(:advertiser_name)
      th = Offer.human_attribute_name(:url)
      th = Offer.human_attribute_name(:description)
      th = Offer.human_attribute_name(:starts_at)
      th = Offer.human_attribute_name(:ends_at)
      th = Offer.human_attribute_name(:premium)
      th = Offer.human_attribute_name(:status)
  tbody
    - @offers.each do |offer|
      tr
        td = offer.advertiser_name
        td = offer.url
        td = offer.description
        td = l(offer.starts_at, format: :short) if offer.starts_at.present?
        td = l(offer.ends_at, format: :short) if offer.ends_at.present?
        td = offer.premium
        td = offer.status
        td = link_to t('actions.edit'), edit_staff_offer_path(offer)
        - if offer.disabled?
          td = link_to t('actions.enable'), enable_staff_offer_path(offer)
        - else
          td = link_to t('actions.disable'), disable_staff_offer_path(offer)
        td = link_to t('actions.destroy'), [:staff, offer], method: :delete, data: { confirm: t('messages.confirm') }

app/views/staff/offers/new.slim
= render 'form'